names = [
    "Liam", "Olivia", "Hiroshi", "Sakura", "Aarav", "Ananya", "Mateo", "Sofia", "Amara", "Lucas",
    "Emma", "Noah", "Ava", "Ethan", "Isabella", "Mia", "Oliver", "Charlotte", "Sophia", "James",
    "Benjamin", "Elijah", "Lucas", "Mason", "Logan", "Alexander", "Ethan", "Jacob", "Michael", "Daniel",
    "Henry", "Jackson", "Sebastian", "Aiden", "Matthew", "Samuel", "David", "Joseph", "Carter", "Owen",
    "Wyatt", "John", "Jack", "Luke", "Julian", "Levi", "Isaac", "Gabriel", "Julian", "Anthony",
    "Santiago", "Valentina", "Matías", "Isabella", "Sebastián", "Camila", "Alejandro", "Valeria", "Diego", "Mariana",
    "Samuel", "Daniela", "Benjamin", "Sofia", "Daniel", "Victoria", "Joaquin", "Luciana", "Tomas", "Antonella",
    "Martin", "Catalina", "Nicolas", "Ignacia", "Gabriel", "Amanda", "Maximiliano", "Martina", "Jose", "Francisca",
    "Mateo", "Laura", "Leonardo", "Luana", "Gabriel", "Ana", "Lucas", "Julia", "Matheus", "Giovanna",
    "Pedro", "Beatriz", "Arthur", "Mariana", "Enzo", "Maria", "Rafael", "Alice", "Joao", "Lara",
    "Kwame", "Ama", "Chioma", "Chukwudi", "Tendai", "Thabo", "Zola", "Jabari", "Nia", "Kofi",
    "Sekai", "Jamil", "Keisha", "Malik", "Imani", "Tunde", "Ife", "Azizi", "Dayo", "Chika",
    "Babajide", "Bunmi", "Dapo", "Eniola", "Femi", "Ganya", "Idi", "Jojo", "Kojo", "Lindiwe",
    "Mandla", "Neo", "Oluchi", "Palesa", "Qasim", "Rafiki", "Sifiso", "Thandiwe", "Unathi", "Vuyo",
    "Wekesa", "Xola", "Yao", "Zola", "Abidemi", "Adebayo", "Bamidele", "Chidinma", "Efe", "Funmilayo",
    "Vihaan", "Sai", "Arjun", "Reyansh", "Vivaan", "Krishna", "Shaurya", "Aadhya", "Diya", "Saanvi",
    "Ananya", "Ishaan", "Kabir", "Advik", "Aarush", "Ishani", "Avani", "Isha", "Kritika", "Meera",
    "Neha", "Poojo", "Priya", "Rahul", "Rohan", "Ryan", "Shreya", "Sneha", "Tanvi", "Yash",
    "Aditya", "Divya", "Riya", "Dev", "Aditi", "Vikram", "Kavita", "Sanjay", "Sunita", "Amit",
    "Geeta", "Anil", "Kiran", "Deepak", "Laxmi", "Rajesh", "Radha", "Suresh", "Swati", "Vivek",
    "In-woo", "Seo-yeon", "Wei", "Mei-ling", "Kenji", "Yuka", "Min-ho", "Ji-young", "Xiang", "Xiaoyan",
    "Takashi", "Aoi", "Daiki", "Hana", "Ren", "Haruto", "Yuna", "Sota", "Riku", "Kaito",
    "Hinata", "Yuto", "Yusei", "Asahi", "Itsuki", "Yuon", "Bo-baee", "Chan-woo", "Dong-hyun", "Eun-ji",
    "Hyun-woo", "Jae-wook", "Ji-hoon", "Jun-ho", "Sang-hoon", "Soo-jin", "Sun-woo", "Woo-jin", "Ye-jun", "Yoo-jung",
    "Jun", "Chao", "Chen", "Dong", "Feng", "Gang", "Hai", "Jian", "Jie", "Lei",
    "Li", "Min", "Ning", "Ping", "Qiang", "Ru", "Tao", "Ting", "Wen", "Wu",
    "Xiang", "Xin", "Yan", "Yang", "Yi", "Yong", "Yu", "Yun", "Zhe", "Zhi",
    "Linh", "Nguyen", "Minh", "Huong", "Anh", "Son", "Thao", "Tuan", "Vy", "Duc",
    "Kanya", "Somchai", "Malee", "Sunan", "Anong", "Somsak", "Kitti", "Niran", "Preecha", "Siriporn",
    "Akbar", "Sita", "Rama", "Lestari", "Putu", "Wayan", "Made", "Nyoman", "Ketut", "Dewi",
    "Tariq", "Layla", "Zainab", "Omar", "Fatima", "Youssef", "Khadija", "Mustafa", "Aisha", "Ahmed",
    "Noor", "Ali", "Mariam", "Bilal", "Amina", "Hamza", "Salma", "Ibrahim", "Yasmin", "Hassan",
    "Khalid", "Farah", "Idris", "Nadia", "Karim", "Mona", "Said", "Reem", "Yassin", "Hoda",
    "Tarek", "Maha", "Mahmoud", "Dina", "Amine", "Hanan", "Nabil", "Rania", "Sami", "Samar",
    "Adel", "Houda", "Mourad", "Souad", "Wafa", "Walid", "Ziad", "Amal", "Bassem", "Ghada",
    "Alejandro", "Camila", "Diego", "Mariana", "Leonardo", "Lucía", "Gabriel", "Martina", "Samuel", "Ximena",
    "Joaquin", "Catalina", "Emiliano", "Valentina", "Lucas", "Antonella", "Felipe", "Isidora", "Martin", "Florencia",
    "Benjamin", "Emilia", "Matias", "Amanda", "Nicolas", "Constanza", "Alonso", "Maite", "Vicente", "Josefa",
    "Thomas", "Chloé", "Nathan", "Léa", "Louis", "Emma", "Jules", "Alice", "Arthur", "Lina",
    "Francesco", "Giulia", "Alessandro", "Aurora", "Mattia", "Sofia", "Leonardo", "Alice", "Tommaso", "Giorgia",
    "Svetlana", "Dmitry", "Nikolai", "Tatiana", "Igor", "Ekaterina", "Elena", "Vladimir", "Anastasia", "Mikhail",
    "Olga", "Ivan", "Nataliya", "Andrey", "Anna", "Sergey", "Maria", "Alexey", "Daria", "Anton",
    "Maxim", "Ksenia", "Ilya", "Veronika", "Pavel", "Victoria", "Artyom", "Polina", "Denis", "Alina",
    "Roman", "Alisa", "Nikita", "Kristina", "Timur", "Valeria", "Kirill", "Regina", "Daniil", "Marina",
    "Egor", "Julia", "Fedor", "Svetlana", "Vadim", "Diana", "Artur", "Nadezhda", "Stepan", "Vera",
    "Miguel", "Sofia", "Juan", "Gabriela", "Pedro", "Francisca", "Manuel", "Josefina", "Carlos", "Antonia",
    "Luis", "Fernanda", "Jose", "Maria", "Jorge", "Camila", "Andres", "Paula", "Javier", "Javiera",
    "Lucas", "Beatriz", "Rodrigo", "Amanda", "Guilherme", "Alice", "Arthur", "Sophia", "Bernardo", "Valentina",
    "Heitor", "Helena", "Davi", "Laura", "Gabriel", "Isabella", "Samuel", "Manuela", "Pedro", "Giovanna",
    "Murilo", "Maria", "Lorenzo", "Yasmin", "Pietro", "Larissa", "Gustavo", "Bruna", "Felipe", "Camila"
]
work_fields = [
    "Information Technology", "Healthcare & Medicine", "Finance & Banking", 
    "Education & Academia", "Engineering", "Marketing & Advertising", 
    "Data Science & Analytics", "Sales & Business Development", 
    "Human Resources", "Legal Services", "Graphic Design & Creative Arts", 
    "Project Management", "Customer Success & Support", "Operations & Logistics", 
    "Biotechnology & Research", "Architecture & Construction", 
    "E-commerce", "Public Relations & Media", "Real Estate", 
    "Environmental Science & Sustainability"
]
countries = [
    "Argentina", "Australia", "Austria", "Bangladesh", "Belgium", 
    "Brazil", "Canada", "Chile", "China", "Colombia", 
    "Denmark", "Egypt", "Finland", "France", "Germany", 
    "Greece", "India", "Indonesia", "Ireland", "Italy", 
    "Japan", "Kazakhstan", "Kenya", "Malaysia", "Mexico", 
    "Morocco", "Netherlands", "New Zealand", "Nigeria", "Norway", 
    "Pakistan", "Peru", "Philippines", "Poland", "Portugal", 
    "Qatar", "Romania", "Saudi Arabia", "Singapore", "South Africa", 
    "South Korea", "Spain", "Sweden", "Switzerland", "Thailand", 
    "Turkey", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", 
    "Vietnam", "Czech Republic", "Hungary", "New Zealand", "Ireland", 
    "Singapore", "Chile", "Ecuador", "Ghana", "Ethiopia"
]